# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
# boosted mod
source:           .
# end boosted mod
destination:      ./_gh_pages
port:             9001
# boosted mod
baseurl:          ""
url:              http://boosted.orange.com/v4-alpha
# end boosted mod
encoding:         UTF-8
exclude:          [img, fonts, .git, .github, assets/scss/, build, js, node_modules, nuget, scss, vendor, bower.json, composer.json, Gemfile, Gemfile.lock, Gruntfile.js, package.js, package.json, package-lock.json,sache.json, bower_components]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# boosted mod
grid:
  xs:
    breakpoint: 0
    width: 302
    gutter: 10
    desc: Extra small devices
    subdesc: Portrait phone (&lt;480px) (target 320 screen resolutions)
  sm:
    breakpoint: 480
    width: 458
    gutter: 10
    desc: Small devices
    subdesc: Landscape phones (&ge;480px - &lt;768px) (target 480 screen resolutions)
  md:
    breakpoint: 768
    width: 724
    gutter: 20
    desc: Medium devices
    subdesc: Tablet (&ge;768px - &lt;960px) (target 768 screen resolutions)
  lg:
    breakpoint: 980
    width: 960
    gutter: 20
    desc: Large devices
    subdesc: Desktop (&ge;960px - &lt;1120px) (target 1024 screen resolutions)
  xl:
    breakpoint: 1220
    width: 1180
    gutter: 20
    desc: Extra large devices
    subdesc: Desktop (&ge;1220px - &lt;1380px) (target 1280 screen resolutions)
  xxl:
    breakpoint: 1380
    width: 1300
    gutter: 20
    desc: Extra extra large devices
    subdesc: Desktop (&ge;1380px) (target 1440 screen resolutions)
# end boosted mod
# Social
title: Boosted
description: Based on Bootstrap the most popular HTML, CSS, and JS library in the world.
twitter: getbootstrap
authors: Mark Otto, Jacob Thornton, and Bootstrap contributors
social_logo_path: /assets/brand/bootstrap-social-logo.png
social_image_path: /assets/brand/bootstrap-social.png

# Custom vars
current_version:  4.0.0-beta.1
docs_version:     4.0
repo:             https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap
slack:            https://bootstrap-slack.herokuapp.com

download:
  source:         https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/archive/v4.0.0-beta.zip
  dist:           https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v4.0.0-beta/boosted-4.0.0-beta-dist.zip

blog:             https://blog.getbootstrap.com
expo:             https://expo.getbootstrap.com
themes:           https://themes.getbootstrap.com
jobs:             https://jobs.getbootstrap.com

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css
  css_hash:       "sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
  js:             https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js
  js_hash:        "sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
  jquery:         https://code.jquery.com/jquery-3.2.1.slim.min.js
  jquery_hash:    "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
  popper:         https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js
  popper_hash:    "sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
