# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
# boosted mod
source:           .tmpdocs
# end boosted mod
destination:      _gh_pages
host:             0.0.0.0
port:             9001
# boosted mod
baseurl:          ""
url:              http://boosted.orange.com/v4-alpha
# end boosted mod
encoding:         UTF-8
exclude:          [assets/scss/]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# boosted mod
grid:
  xs:
    breakpoint: 0
    width: 302 
    gutter: 10
    desc: Extra small devices
    subdesc: Portrait phone (&lt;480px) (target 320 screen resolutions)
  sm:
    breakpoint: 480
    width: 458 
    gutter: 10
    desc: Small devices
    subdesc: Landscape phones (&ge;480px - &lt;768px) (target 480 screen resolutions)
  md:
    breakpoint: 768
    width: 724 
    gutter: 20
    desc: Medium devices
    subdesc: Tablet (&ge;768px - &lt;960px) (target 768 screen resolutions)
  lg:
    breakpoint: 980
    width: 960 
    gutter: 20
    desc: Large devices
    subdesc: Desktop (&ge;960px - &lt;1120px) (target 1024 screen resolutions)
  xl:
    breakpoint: 1220
    width: 1180 
    gutter: 20
    desc: Extra large devices
    subdesc: Desktop (&ge;1220px - &lt;1380px) (target 1280 screen resolutions)
  xxl:
    breakpoint: 1380
    width: 1300 
    gutter: 20
    desc: Extra extra large devices
    subdesc: Desktop (&ge;1380px) (target 1440 screen resolutions)
# end boosted mod
# Custom vars
current_version:  4.0.0-alpha.2
repo:             https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap
slack:            https://bootstrap-slack.herokuapp.com

download:
  source:         https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/archive/v4.0.0-alpha.2.zip
  dist:           https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v4.0.0/boosted-4.0.0-alpha.2-dist.zip

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com
themes:           http://themes.getbootstrap.com

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css
  css_hash:       "sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd"
  js:             https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js
  js_hash:        "sha384-vZ2WRJMwsjRMW/8U7i6PWi6AlO1L79snBrmgiDpgIWJ82z8eA5lenwvxbMV1PAh7"
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js
  jquery_hash:    "sha384-mXQoED/lFIuocc//nss8aJOIrz7X7XruhR6bO+sGceiSyMELoVdZkN7F0oYwcFH+"
  tether:         https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js
  tether_hash:    "sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB"
