# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "site"
destination:    ./_gh_pages
host:           "localhost"
port:           9001
baseurl:        ""
# boosted mod
url:            https://boosted.orange.com
# end boosted mod
encoding:       UTF-8
exclude:
  - docs/4.3/assets/scss/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# boosted mod
grid:
  xs:
    breakpoint: 0
    width: 302
    gutter: 10
    desc: Extra small devices
    subdesc: Portrait phone (&lt;480px) (target 320 screen resolutions)
  sm:
    breakpoint: 480
    width: 458
    gutter: 10
    desc: Small devices
    subdesc: Landscape phones (&ge;480px - &lt;768px) (target 480 screen resolutions)
  md:
    breakpoint: 768
    width: 724
    gutter: 20
    desc: Medium devices
    subdesc: Tablet (&ge;768px - &lt;960px) (target 768 screen resolutions)
  lg:
    breakpoint: 980
    width: 960
    gutter: 20
    desc: Large devices
    subdesc: Desktop (&ge;960px - &lt;1120px) (target 1024 screen resolutions)
  xl:
    breakpoint: 1220
    width: 1180
    gutter: 20
    desc: Extra large devices
    subdesc: Desktop (&ge;1220px - &lt;1380px) (target 1280 screen resolutions)
  xxl:
    breakpoint: 1380
    width: 1300
    gutter: 20
    desc: Extra extra large devices
    subdesc: Desktop (&ge;1380px) (target 1440 screen resolutions)
# end boosted mod
# Social
title:              Boosted
description:        "Based on Bootstrap the most popular library."
twitter:            getbootstrap
authors:            "Mark Otto, Jacob Thornton, and Bootstrap contributors"
social_image_path:  /docs/4.2/assets/brand/bootstrap-social.png
social_logo_path:   /docs/4.2/assets/brand/bootstrap-social-logo.png

# Custom variables
current_version:      4.2.2
bootstrap_current_version:      v4.2.1
current_ruby_version: 4.2.2
docs_version:         4.2
repo:                 "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap"
slack:                "https://bootstrap-slack.herokuapp.com"
blog:                 "https://blog.getbootstrap.com"
expo:                 "https://expo.getbootstrap.com"
themes:               "https://themes.getbootstrap.com"

download:
  source:           "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/archive/v4.2.2.zip"
  dist:             "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v4.2.2/boosted-4.2.2-dist.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:              "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
  css_hash:         "sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
  js:               "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
  js_hash:          "sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
  js_bundle:        "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js"
  js_bundle_hash:   "sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP"
  jquery:           "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  jquery_hash:      "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
  popper_hash:      "sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
  tablesorter:      "https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.29.4/js/jquery.tablesorter.min.js"
  tablesorter_hash: "sha256-eMa5IMxi2DRTBbnBSoK/sTKxDkVo8uqM7jMgKFfMoiU="

toc:
  min_level:        2
  max_level:        4
  no_toc_section_class:
    - "bd-callout"
    - "bd-example"
