languageCode:                       "en"
title:                              "Boosted"
baseURL:                            "https://deploy-preview-1536--boosted.netlify.app"

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:                       true
  highlight:
    noClasses:                      false
  tableOfContents:
    startLevel:                     2
    endLevel:                       6

buildDrafts:                        true
buildFuture:                        true

enableRobotsTXT:                    true
metaDataFormat:                     "yaml"
disableKinds:                       ["404", "taxonomy", "term", "RSS"]

publishDir:                         "_site"

module:
  mounts:
    - source:                       dist
      target:                       static/docs/5.2/dist
    - source:                       site/assets
      target:                       assets
    - source:                       site/content
      target:                       content
    - source:                       site/data
      target:                       data
    - source:                       site/layouts
      target:                       layouts
    - source:                       site/static
      target:                       static
    - source:                       site/static/docs/5.2/assets/img/favicons/apple-touch-icon.png
      target:                       static/apple-touch-icon.png
    - source:                       site/static/docs/5.2/assets/img/favicons/favicon.ico
      target:                       static/favicon.ico

      # Boosted mod
    - source:                       node_modules/tarteaucitronjs/tarteaucitron.js
      target:                       assets/js/vendor/tarteaucitron.js
    - source:                       node_modules/tarteaucitronjs/lang
      target:                       static/docs/5.2/assets/js/lang

params:
  subtitle:                         "Boosted Innovation Cup with Bootstrap is a Bootstrap based, Orange branded accessible and ergonomic components library…"
  description:                      "Powerful, extensible, and feature-packed frontend toolkit. Build and customize with Sass, utilize prebuilt grid system and components, and bring projects to life with powerful JavaScript plugins."
  authors:                          "Orange and Boosted contributors"

  current_version:                  "5.2.1"
  current_ruby_version:             "5.2.1"
  docs_version:                     "5.2"
  rfs_version:                      "v9.0.6"
  repo:                             "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap"
  twitter:                          "getbootstrap"
  blog:                             "https://blog.getbootstrap.com/"
  bootstrap:                        "https://getbootstrap.com"

  download:
    source:                         "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/archive/v5.2.1.zip"
    dist:                           "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v5.2.1/boosted-innovation-cup-5.2.1-dist.zip"
    dist_examples:                  "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v5.2.1/boosted-innovation-cup-5.2.1-examples.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:                            "https://cdn.jsdelivr.net/npm/boosted-innovation-cup@5.2.1/dist/css/boosted.min.css"
    css_hash:                       "sha384-CYwBBOBitXWralvRBTTEteu86YHHydT/+Wsv4kmxP6oF/SaesPQeMxLbblEUyZf/"
    css_rtl:                        "https://cdn.jsdelivr.net/npm/boosted-innovation-cup@5.2.1/dist/css/boosted.rtl.min.css"
    css_rtl_hash:                   "sha384-dmnbBbP2SVkMFPx/rM/ySY8ibT3vQlnqL3pS2VGfxR6Ts0zQlKYUqnPXyJ9Q7kyG"
    js:                             "https://cdn.jsdelivr.net/npm/boosted-innovation-cup@5.2.1/dist/js/boosted.min.js"
    js_hash:                        "sha384-GBfyQzRj/34bRvjbWfsgvYvEqkV+YniZdXAuu66ZVhSPIdzVzVouXBJBjpd58tcY"
    js_bundle:                      "https://cdn.jsdelivr.net/npm/boosted-innovation-cup@5.2.1/dist/js/boosted.bundle.min.js"
    js_bundle_hash:                 "sha384-NkAB+hiFHsv6dxwL0C4lJtfq1RblxY6+DRFn5QZDpgCdwB5RiOGjaJB0Weq0uCy3"
    popper:                         "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    popper_hash:                    "sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
    focus_visible:                  "https://cdn.jsdelivr.net/npm/focus-visible@5.2.0/dist/focus-visible.min.js"
    focus_visible_hash:             "sha384-xRa5B8rCDfdg0npZcxAh+RXswrbFk3g6dlHVeABeluN8EIwdyljz/LqJgc2R3KNA"

  anchors:
    min: 2
    max: 5
